;; Every supported i64 ordering comparison contributes one bit. The function
;; returns 255 only when signed high-word ordering and unsigned low-word
;; tie-breaking both follow Wasm semantics.
(module
  (type $point (func (param i32 i32)))
  (type $entry (func (result i32)))
  (import "env" "vircon_gpu_set_drawing_point" (func $point (type $point)))
  (memory 17)
  (export "memory" (memory 0))
  (func $main (type $entry)
    (local $result i32)
    (local.set $result (i64.lt_s (i64.const -1) (i64.const 0)))
    (local.set $result (i32.or (local.get $result)
      (i32.shl (i64.le_s (i64.const -1) (i64.const 0)) (i32.const 1))))
    (local.set $result (i32.or (local.get $result)
      (i32.shl (i64.gt_s (i64.const 0) (i64.const -1)) (i32.const 2))))
    (local.set $result (i32.or (local.get $result)
      (i32.shl (i64.ge_s (i64.const 0) (i64.const -1)) (i32.const 3))))
    (local.set $result (i32.or (local.get $result)
      (i32.shl (i64.lt_u (i64.const 0) (i64.const -1)) (i32.const 4))))
    (local.set $result (i32.or (local.get $result)
      (i32.shl (i64.le_u (i64.const 0) (i64.const -1)) (i32.const 5))))
    (local.set $result (i32.or (local.get $result)
      (i32.shl (i64.gt_u (i64.const -1) (i64.const 0)) (i32.const 6))))
    (local.set $result (i32.or (local.get $result)
      (i32.shl (i64.ge_u (i64.const -1) (i64.const 0)) (i32.const 7))))
    (call $point (local.get $result) (i32.const 0))
    (local.get $result))
  (export "main" (func $main)))
