# Cross-platform C-to-ROM integration runner driven by per-case testcases metadata.
#
# This deliberately mirrors the supported frontend contract without invoking
# the public CMake ROM driver. Keeping the test harness in CMake makes CTest
# usable with native Windows tool installations.

foreach(required_variable IN ITEMS TOOL CLANG WASM_LD ASSEMBLE PACKROM PNG2VIRCON WAV2VIRCON TILED2VIRCON TESTS_DIR)
  if(NOT DEFINED ${required_variable})
    message(FATAL_ERROR "run-rom-tests.cmake requires -D${required_variable}=...")
  endif()
endforeach()

if(NOT DEFINED TEST_MODE)
  set(TEST_MODE all)
endif()
if(NOT TEST_MODE STREQUAL "all" AND NOT TEST_MODE STREQUAL "simulator")
  message(FATAL_ERROR "unknown test mode: ${TEST_MODE}")
endif()
if(TEST_MODE STREQUAL "simulator")
  if(NOT DEFINED V32SIM OR NOT DEFINED V32SIM_BIOS)
    message(FATAL_ERROR "simulator tests require V32SIM and V32SIM_BIOS")
  endif()
endif()

# Fail with the command's complete output, which is substantially more useful
# than a platform-specific shell error when an installed tool rejects a case.
function(run_required context)
  execute_process(
    COMMAND ${ARGN}
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${context} failed (exit ${result}):\n${output}${error}")
  endif()
endfunction()

# Read the intentionally small key=value format shared by all test cases.
function(read_case_metadata metadata_file prefix)
  file(STRINGS "${metadata_file}" metadata_lines)
  foreach(line IN LISTS metadata_lines)
    if(line MATCHES "^[ \\t]*(#|$)")
      continue()
    endif()
    string(FIND "${line}" "=" separator)
    if(separator EQUAL -1)
      message(FATAL_ERROR "${metadata_file}: expected key=value metadata")
    endif()
    string(SUBSTRING "${line}" 0 ${separator} key)
    math(EXPR value_start "${separator} + 1")
    string(SUBSTRING "${line}" ${value_start} -1 value)
    set(supported_keys
      source wasm_as_options entry expectations error_expectations outcome
      extra_sources include_dirs textures sounds embedded_words tilemaps
      xml_expectations normalize allow_stack_pointer skip_input_optimization
      cli_inspection cli_only sim_commands sim_expectations sim_watch_for sim_stdin)
    list(FIND supported_keys "${key}" supported_key_index)
    if(supported_key_index EQUAL -1)
      message(FATAL_ERROR "${metadata_file}: unknown key: ${key}")
    endif()
    set("${prefix}_${key}" "${value}" PARENT_SCOPE)
  endforeach()
endfunction()

# Test expectation files hold literal, nonempty assembly/XML output fragments.
function(require_expectations case_name artifact expectation_file artifact_kind)
  if(NOT EXISTS "${expectation_file}")
    message(FATAL_ERROR "${case_name}: missing ${artifact_kind} expectations: ${expectation_file}")
  endif()
  file(READ "${artifact}" artifact_text)
  file(STRINGS "${expectation_file}" expected_fragments)
  foreach(fragment IN LISTS expected_fragments)
    if(fragment MATCHES "^[ \\t]*(#|$)")
      continue()
    endif()
    string(FIND "${artifact_text}" "${fragment}" found)
    if(found EQUAL -1)
      message(FATAL_ERROR "${case_name}: ${artifact_kind} lacks expected fragment: ${fragment}")
    endif()
  endforeach()
endfunction()

# Convert a project-supplied little-endian word file to the small C definition
# used by the tile-map cases, without requiring host command-line text utilities.
function(write_embedded_words output_c identifier input_words)
  if(NOT identifier MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    message(FATAL_ERROR "embedded word name is not a C identifier: ${identifier}")
  endif()
  if(NOT EXISTS "${input_words}")
    message(FATAL_ERROR "embedded word file not found: ${input_words}")
  endif()
  file(READ "${input_words}" words_hex HEX)
  string(LENGTH "${words_hex}" hex_length)
  math(EXPR byte_count "${hex_length} / 2")
  math(EXPR trailing_bytes "${byte_count} % 4")
  if(NOT trailing_bytes EQUAL 0)
    message(FATAL_ERROR "embedded word file is not a whole number of 32-bit words: ${input_words}")
  endif()

  set(source "/* Generated from a project-supplied little-endian word asset. */\nconst int ${identifier}[] = {\n")
  math(EXPR word_count "${byte_count} / 4")
  if(word_count GREATER 0)
    math(EXPR last_word "${word_count} - 1")
    foreach(word_index RANGE 0 ${last_word})
      math(EXPR byte_offset "${word_index} * 8")
      string(SUBSTRING "${words_hex}" ${byte_offset} 2 byte_0)
      math(EXPR byte_offset "${byte_offset} + 2")
      string(SUBSTRING "${words_hex}" ${byte_offset} 2 byte_1)
      math(EXPR byte_offset "${byte_offset} + 2")
      string(SUBSTRING "${words_hex}" ${byte_offset} 2 byte_2)
      math(EXPR byte_offset "${byte_offset} + 2")
      string(SUBSTRING "${words_hex}" ${byte_offset} 2 byte_3)
      math(EXPR line_position "${word_index} % 8")
      if(line_position EQUAL 0)
        string(APPEND source "    ")
      endif()
      string(APPEND source "(int)0x${byte_3}${byte_2}${byte_1}${byte_0}U, ")
      if(line_position EQUAL 7)
        string(APPEND source "\n")
      endif()
    endforeach()
    math(EXPR final_position "${last_word} % 8")
    if(NOT final_position EQUAL 7)
      string(APPEND source "\n")
    endif()
  endif()
  string(APPEND source "};\n")
  file(WRITE "${output_c}" "${source}")
endfunction()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef work_suffix)
set(work_dir "${CMAKE_CURRENT_BINARY_DIR}/wasm2vircon-rom-tests-${work_suffix}")
file(MAKE_DIRECTORY "${work_dir}")

file(GLOB case_directories LIST_DIRECTORIES true "${TESTS_DIR}/c-*")
list(SORT case_directories)
set(found_c_case OFF)
set(found_simulator_case OFF)
foreach(case_directory IN LISTS case_directories)
  set(metadata_file "${case_directory}/testcases")
  if(NOT EXISTS "${metadata_file}")
    continue()
  endif()

  # Reset every optional field so one case cannot leak metadata into another.
  foreach(key IN ITEMS
      source wasm_as_options entry expectations error_expectations outcome
      extra_sources include_dirs textures sounds embedded_words tilemaps
      xml_expectations normalize allow_stack_pointer skip_input_optimization
      cli_inspection cli_only sim_commands sim_expectations sim_watch_for sim_stdin)
    set("case_${key}" "")
  endforeach()
  set(case_entry main)
  set(case_normalize false)
  set(case_allow_stack_pointer false)
  read_case_metadata("${metadata_file}" case)

  if(NOT case_source MATCHES "\\.c$")
    continue()
  endif()
  if(TEST_MODE STREQUAL "simulator" AND case_sim_commands STREQUAL "")
    continue()
  endif()

  set(found_c_case ON)
  if(TEST_MODE STREQUAL "simulator")
    set(found_simulator_case ON)
  endif()
  set(case_name "${case_directory}")
  get_filename_component(case_name "${case_name}" NAME)
  set(source_path "${case_directory}/${case_source}")
  if(NOT EXISTS "${source_path}")
    message(FATAL_ERROR "${case_name}: source file not found: ${source_path}")
  endif()
  if(NOT case_normalize STREQUAL "true" AND NOT case_normalize STREQUAL "false")
    message(FATAL_ERROR "${case_name}: normalize must be true or false")
  endif()
  if(NOT case_allow_stack_pointer STREQUAL "true" AND NOT case_allow_stack_pointer STREQUAL "false")
    message(FATAL_ERROR "${case_name}: allow_stack_pointer must be true or false")
  endif()

  set(case_output "${work_dir}/${case_name}")
  file(MAKE_DIRECTORY "${case_output}")
  get_filename_component(program_name "${case_source}" NAME_WE)
  set(wasm_file "${case_output}/${program_name}.wasm")
  set(asm_file "${case_output}/${program_name}.asm")
  set(vbin_file "${case_output}/${program_name}.vbin")
  set(xml_file "${case_output}/${program_name}.xml")
  set(rom_file "${case_output}/${program_name}.v32")

  set(clang_flags --target=wasm32-unknown-unknown -O2 -fno-jump-tables -ffreestanding -fno-builtin -nostdlib)
  separate_arguments(include_directories NATIVE_COMMAND "${case_include_dirs}")
  foreach(include_directory IN LISTS include_directories)
    set(include_path "${case_directory}/${include_directory}")
    if(NOT IS_DIRECTORY "${include_path}")
      message(FATAL_ERROR "${case_name}: include directory not found: ${include_path}")
    endif()
    list(APPEND clang_flags -I "${include_path}")
  endforeach()

  # Convert tile-map output into another embedded little-endian word asset.
  separate_arguments(embedded_specs NATIVE_COMMAND "${case_embedded_words}")
  separate_arguments(tilemap_specs NATIVE_COMMAND "${case_tilemaps}")
  foreach(tilemap_spec IN LISTS tilemap_specs)
    string(FIND "${tilemap_spec}" "=" equals)
    if(equals EQUAL -1)
      message(FATAL_ERROR "${case_name}: tilemap must use NAME=TMX: ${tilemap_spec}")
    endif()
    string(SUBSTRING "${tilemap_spec}" 0 ${equals} tilemap_name)
    math(EXPR tilemap_source_start "${equals} + 1")
    string(SUBSTRING "${tilemap_spec}" ${tilemap_source_start} -1 tilemap_source)
    set(tilemap_path "${case_directory}/${tilemap_source}")
    if(NOT EXISTS "${tilemap_path}")
      message(FATAL_ERROR "${case_name}: tilemap source not found: ${tilemap_path}")
    endif()
    list(LENGTH embedded_specs tilemap_index)
    set(tilemap_output "${case_output}/tilemap-${tilemap_index}")
    file(MAKE_DIRECTORY "${tilemap_output}")
    run_required("${case_name}: tiled2vircon" "${TILED2VIRCON}" "${tilemap_path}" -o "${tilemap_output}/")
    file(GLOB generated_tilemaps "${tilemap_output}/*.vmap")
    list(LENGTH generated_tilemaps generated_count)
    if(NOT generated_count EQUAL 1)
      message(FATAL_ERROR "${case_name}: tilemap must generate exactly one .vmap file")
    endif()
    list(GET generated_tilemaps 0 generated_tilemap)
    list(APPEND embedded_specs "${tilemap_name}=${generated_tilemap}")
  endforeach()

  set(generated_sources "")
  foreach(embedded_spec IN LISTS embedded_specs)
    string(FIND "${embedded_spec}" "=" equals)
    if(equals EQUAL -1)
      message(FATAL_ERROR "${case_name}: embedded words must use NAME=FILE: ${embedded_spec}")
    endif()
    string(SUBSTRING "${embedded_spec}" 0 ${equals} embedded_name)
    math(EXPR embedded_path_start "${equals} + 1")
    string(SUBSTRING "${embedded_spec}" ${embedded_path_start} -1 embedded_relative_path)
    set(embedded_path "${embedded_relative_path}")
    if(NOT IS_ABSOLUTE "${embedded_path}")
      set(embedded_path "${case_directory}/${embedded_path}")
    endif()
    list(LENGTH generated_sources generated_index)
    set(generated_source "${case_output}/${program_name}.embedded-${generated_index}.c")
    write_embedded_words("${generated_source}" "${embedded_name}" "${embedded_path}")
    list(APPEND generated_sources "${generated_source}")
  endforeach()

  separate_arguments(extra_sources NATIVE_COMMAND "${case_extra_sources}")
  set(sources "${source_path}")
  foreach(extra_source IN LISTS extra_sources)
    set(extra_source_path "${case_directory}/${extra_source}")
    if(NOT EXISTS "${extra_source_path}")
      message(FATAL_ERROR "${case_name}: extra source not found: ${extra_source_path}")
    endif()
    list(APPEND sources "${extra_source_path}")
  endforeach()
  list(APPEND sources ${generated_sources})

  list(LENGTH sources source_count)
  # `normalize=true` in shared metadata means this case must use wasm-ld's
  # normal linked-module shape.  Do not run wasm-opt here: the integration
  # suite intentionally verifies compiler-owned linker-artifact legalization.
  if(case_normalize STREQUAL "false" AND source_count EQUAL 1)
    run_required("${case_name}: clang direct Wasm link" "${CLANG}" ${clang_flags} "${source_path}"
      "-Wl,--no-entry" "-Wl,--export=${case_entry}" "-Wl,--allow-undefined" -o "${wasm_file}")
  else()
    set(objects "")
    foreach(source IN LISTS sources)
      list(LENGTH objects object_index)
      set(object_file "${case_output}/${program_name}.part-${object_index}.o")
      run_required("${case_name}: clang compile" "${CLANG}" ${clang_flags} -c "${source}" -o "${object_file}")
      list(APPEND objects "${object_file}")
    endforeach()
    run_required("${case_name}: wasm-ld" "${WASM_LD}" --no-entry "--export=${case_entry}" --allow-undefined
      ${objects} -o "${wasm_file}")
  endif()
  set(compiler_arguments "${wasm_file}" --entry "${case_entry}")
  if(case_allow_stack_pointer STREQUAL "true")
    list(APPEND compiler_arguments --allow-stack-pointer)
  endif()
  list(APPEND compiler_arguments -o "${asm_file}")
  run_required("${case_name}: wasm2vircon" "${TOOL}" ${compiler_arguments})
  run_required("${case_name}: assemble" "${ASSEMBLE}" -o "${vbin_file}" "${asm_file}")

  set(texture_outputs "")
  separate_arguments(textures NATIVE_COMMAND "${case_textures}")
  foreach(texture IN LISTS textures)
    set(texture_path "${case_directory}/${texture}")
    if(NOT EXISTS "${texture_path}")
      message(FATAL_ERROR "${case_name}: texture source not found: ${texture_path}")
    endif()
    list(LENGTH texture_outputs texture_index)
    set(texture_name "texture-${texture_index}.vtex")
    run_required("${case_name}: png2vircon" "${PNG2VIRCON}" "${texture_path}" -o "${case_output}/${texture_name}")
    list(APPEND texture_outputs "${texture_name}")
  endforeach()

  set(sound_outputs "")
  separate_arguments(sounds NATIVE_COMMAND "${case_sounds}")
  foreach(sound IN LISTS sounds)
    set(sound_path "${case_directory}/${sound}")
    if(NOT EXISTS "${sound_path}")
      message(FATAL_ERROR "${case_name}: sound source not found: ${sound_path}")
    endif()
    list(LENGTH sound_outputs sound_index)
    set(sound_name "sound-${sound_index}.vsnd")
    run_required("${case_name}: wav2vircon" "${CMAKE_COMMAND}" -E env SDL_AUDIODRIVER=dummy
      "${WAV2VIRCON}" "${sound_path}" -o "${case_output}/${sound_name}")
    list(APPEND sound_outputs "${sound_name}")
  endforeach()

  file(WRITE "${xml_file}" "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>\n<rom-definition version=\"1.0\">\n")
  file(APPEND "${xml_file}" "  <rom type=\"cartridge\" title=\"${program_name}\" version=\"1.0\" />\n  <binary path=\"${program_name}.vbin\" />\n  <textures>\n")
  foreach(texture_name IN LISTS texture_outputs)
    file(APPEND "${xml_file}" "    <texture path=\"${texture_name}\" />\n")
  endforeach()
  file(APPEND "${xml_file}" "  </textures>\n  <sounds>\n")
  foreach(sound_name IN LISTS sound_outputs)
    file(APPEND "${xml_file}" "    <sound path=\"${sound_name}\" />\n")
  endforeach()
  file(APPEND "${xml_file}" "  </sounds>\n</rom-definition>\n")
  run_required("${case_name}: packrom" "${PACKROM}" -o "${rom_file}" "${xml_file}")
  if(NOT EXISTS "${rom_file}")
    message(FATAL_ERROR "${case_name}: packrom did not create ${rom_file}")
  endif()

  if(NOT case_expectations STREQUAL "")
    require_expectations("${case_name}" "${asm_file}" "${case_directory}/${case_expectations}" "assembly")
  endif()
  if(NOT case_xml_expectations STREQUAL "")
    require_expectations("${case_name}" "${xml_file}" "${case_directory}/${case_xml_expectations}" "ROM XML")
  endif()

  if(TEST_MODE STREQUAL "simulator")
    if(case_sim_expectations STREQUAL "")
      message(FATAL_ERROR "${case_name}: simulator cases require sim_expectations")
    endif()
    set(simulation_output "${case_output}/${program_name}.v32sim.out")
    set(simulator_arguments --no-debug --run --errorcheck --biosfile "${V32SIM_BIOS}"
      --entry-point 0x20000000 --command-file "${case_directory}/${case_sim_commands}")
    if(NOT case_sim_watch_for STREQUAL "")
      list(APPEND simulator_arguments --watch-for "${case_sim_watch_for}")
    endif()
    list(APPEND simulator_arguments "${rom_file}")
    set(simulator_input_arguments "")
    if(NOT case_sim_stdin STREQUAL "")
      list(APPEND simulator_input_arguments INPUT_FILE "${case_directory}/${case_sim_stdin}")
    endif()
    execute_process(
      COMMAND "${V32SIM}" ${simulator_arguments}
      ${simulator_input_arguments}
      RESULT_VARIABLE simulator_result
      OUTPUT_VARIABLE simulator_stdout
      ERROR_VARIABLE simulator_stderr)
    file(WRITE "${simulation_output}" "${simulator_stdout}${simulator_stderr}")
    if(NOT simulator_result EQUAL 0)
      message(FATAL_ERROR "${case_name}: v32sim failed (exit ${simulator_result}):\n${simulator_stdout}${simulator_stderr}")
    endif()
    require_expectations("${case_name}" "${simulation_output}" "${case_directory}/${case_sim_expectations}" "simulator output")
  endif()
endforeach()

if(TEST_MODE STREQUAL "all" AND NOT found_c_case)
  message(FATAL_ERROR "no C testcases files found under ${TESTS_DIR}/c-*")
endif()
if(TEST_MODE STREQUAL "simulator" AND NOT found_simulator_case)
  message(FATAL_ERROR "no simulator testcases files found under ${TESTS_DIR}/c-*")
endif()

file(REMOVE_RECURSE "${work_dir}")
