out GPU_RegionMinX, R1
out GPU_RegionMinY, R2
out GPU_RegionMaxX, R1
out GPU_RegionMaxY, R2
out GPU_RegionHotSpotX, R1
out GPU_RegionHotSpotY, R2
out SPU_SelectedChannel, R1
out SPU_ChannelAssignedSound, R1
out SPU_Command, SPUCommand_PlaySelectedChannel
