(module
  (type $one (func (param i32)))
  (type $two (func (param i32 i32)))
  (type $none (func))
  (type $entry (func (result i32)))
  (import "env" "vircon_gpu_set_region_minimum" (func $minimum (type $two)))
  (import "env" "vircon_gpu_set_region_maximum" (func $maximum (type $two)))
  (import "env" "vircon_gpu_set_region_hotspot" (func $hotspot (type $two)))
  (import "env" "vircon_spu_select_channel" (func $channel (type $one)))
  (import "env" "vircon_spu_set_channel_assigned_sound" (func $sound (type $one)))
  (import "env" "vircon_spu_play_selected_channel" (func $play (type $none)))
  (memory 1)
  (func $main (type $entry)
    (call $minimum (i32.const 0) (i32.const 0))
    (call $maximum (i32.const 139) (i32.const 99))
    (call $hotspot (i32.const 69) (i32.const 49))
    (call $channel (i32.const 0))
    (call $sound (i32.const 0))
    (call $play)
    (i32.const 0))
  (export "__original_main" (func $main)))
