(module
  (memory 1)
  (func $identity (param $value i32) (result i32)
    (local.get $value))
  (func $sum4 (param $a i32) (param $b i32) (param $c i32) (param $d i32) (result i32)
    (i32.add (local.get $a)
      (i32.add (local.get $b)
        (i32.add (local.get $c) (local.get $d)))))
  (func $caller (param $a i32) (param $b i32) (param $c i32) (param $d i32) (result i32)
    (local $saved i32)
    (local.set $saved (local.get $a))
    (call $sum4
      (local.get $saved)
      (call $identity (local.get $b))
      (call $identity (local.get $c))
      (call $identity (local.get $d))))
  (func $entry (result i32)
    (call $caller (i32.const 1) (i32.const 2) (i32.const 3) (i32.const 4)))
  (export "__original_main" (func $entry))
)
