(module
  (type $void_i32 (func (param i32)))
  (type $i32 (func (result i32)))
  (import "env" "vircon_gpu_set_multiply_color" (func $set_color (type $void_i32)))
  (import "env" "vircon_input_select_gamepad" (func $select_gamepad (type $void_i32)))
  (import "env" "vircon_input_gamepad_left" (func $left (type $i32)))
  (import "env" "vircon_input_gamepad_right" (func $right (type $i32)))
  (import "env" "vircon_input_gamepad_up" (func $up (type $i32)))
  (import "env" "vircon_input_gamepad_down" (func $down (type $i32)))
  (import "env" "vircon_timer_get_frame_counter" (func $frame (type $i32)))
  (memory 1)
  (func (export "__original_main") (result i32)
    (local $value i32)
    (call $set_color (i32.const -1))
    (call $select_gamepad (i32.const 0))
    (local.set $value (call $left))
    (local.set $value (call $right))
    (local.set $value (call $up))
    (local.set $value (call $down))
    (local.set $value (call $frame))
    (local.set $value (i32.sub (i32.const 8) (i32.const 3)))
    (local.set $value (i32.mul (local.get $value) (i32.const 4)))
    (local.set $value (i32.div_u (i32.const -1) (i32.const 2)))
    (local.set $value (i32.rem_s (i32.const -7) (i32.const 3)))
    (local.set $value (i32.shl (i32.const 1) (i32.const 33)))
    (local.set $value (i32.ne (i32.const 1) (i32.const 2)))
    (local.set $value (i32.lt_s (i32.const -1) (i32.const 0)))
    (local.set $value (i32.lt_u (i32.const -1) (i32.const 0)))
    (local.set $value (i32.gt_s (i32.const 1) (i32.const 0)))
    (local.set $value (i32.gt_u (i32.const -1) (i32.const 0)))
    (local.set $value (i32.ge_s (i32.const 0) (i32.const 0)))
    (i32.store (i32.const 0) (local.get $value))
    (i32.load (i32.const 0))
  )
)
