(module
  (type $void (func))
  (type $void_i32 (func (param i32)))
  (type $void_i32_i32 (func (param i32 i32)))
  (type $i32 (func (result i32)))
  (import "env" "vircon_gpu_set_drawing_scale_bits" (func $scale (type $void_i32_i32)))
  (import "env" "vircon_gpu_draw_region_zoomed" (func $zoom (type $void)))
  (import "env" "vircon_input_gamepad_connected" (func $connected (type $i32)))
  (import "env" "vircon_input_gamepad_button_a" (func $a (type $i32)))
  (import "env" "vircon_input_gamepad_button_b" (func $b (type $i32)))
  (import "env" "vircon_input_gamepad_button_x" (func $x (type $i32)))
  (import "env" "vircon_input_gamepad_button_y" (func $y (type $i32)))
  (import "env" "vircon_input_gamepad_button_l" (func $l (type $i32)))
  (import "env" "vircon_input_gamepad_button_r" (func $r (type $i32)))
  (import "env" "vircon_input_gamepad_button_start" (func $start (type $i32)))
  (memory 1)
  (func (export "__original_main") (result i32)
    (local i32)
    (call $scale (i32.const 0x43A00000) (i32.const 0x3F800000))
    (call $zoom)
    (local.set 0 (call $connected))
    (local.set 0 (call $a))
    (local.set 0 (call $b))
    (local.set 0 (call $x))
    (local.set 0 (call $y))
    (local.set 0 (call $l))
    (local.set 0 (call $r))
    (local.set 0 (call $start))
    (local.get 0)))
