(module
  (type $void (func))
  (type $i32 (func (param i32)))
  (type $f32 (func (param f32)))
  (import "env" "vircon_spu_set_sound_loop_start" (func $set_loop_start (type $i32)))
  (import "env" "vircon_spu_set_sound_loop_end" (func $set_loop_end (type $i32)))
  (import "env" "vircon_spu_set_channel_loop_enabled" (func $set_channel_loop (type $i32)))
  (import "env" "vircon_spu_set_global_volume" (func $set_global_volume (type $f32)))
  (import "env" "vircon_spu_pause_selected_channel" (func $pause_selected (type $void)))
  (memory 1)
  (func (export "__original_main") (result i32)
    (call $set_loop_start (i32.const 9081))
    (call $set_loop_end (i32.const 15655))
    (call $set_channel_loop (i32.const 0))
    (call $set_global_volume (f32.const 0.5))
    (call $pause_selected)
    (i32.const 0)))
