(module
  (type $void (func))
  (type $one (func (param i32)))
  (type $two (func (param i32 i32)))
  (type $get (func (result i32)))
  (import "env" "vircon_gpu_get_selected_texture" (func $get_texture (type $get)))
  (import "env" "vircon_gpu_select_texture" (func $select_texture (type $one)))
  (import "env" "vircon_gpu_select_region" (func $select_region (type $one)))
  (import "env" "vircon_gpu_set_drawing_point" (func $set_point (type $two)))
  (import "env" "vircon_gpu_draw_region" (func $draw_region (type $void)))
  (memory 1)
  (func $main (result i32)
    (local $texture i32)
    (local.set $texture (call $get_texture))
    (call $select_texture (i32.const -1))
    (call $select_region (i32.const 65))
    (call $set_point (i32.const 10) (i32.const 20))
    (call $draw_region)
    (call $select_texture (local.get $texture))
    (i32.const 0))
  (export "__original_main" (func $main)))
