/*
 * Vircon32 assembly emitter.
 *
 * This is the only compiler stage that knows the textual spelling of V32 IR
 * nodes. Frontend lowering and future optimization passes operate on typed
 * opcodes and operands instead of parsing or rewriting assembler text.
 */

#include "emitter.h"

#include <inttypes.h>
#include <stdio.h>

/* Canonical assembler spellings are deliberately owned by this emitter. */
static const char *const OPCODE_NAMES[VIRCON_IR_OPCODE_COUNT] = {
    "mov",  "push", "pop",   "call", "ret",   "hlt",  "jmp",  "jt",   "jf",   "wait", "iadd",
    "isub", "imul", "idiv",  "imod", "and",   "or",   "xor",  "shl",  "ieq",  "ine",  "ilt",
    "ile",  "igt",  "ige",   "fadd", "fsub",  "fmul", "fdiv", "fmod", "feq",  "fne",  "flt",
    "fle",  "fgt",  "fge",   "cif",  "cfi",   "fsgn", "fabs", "flr",  "ceil", "round", "sin",
    "acos", "log",  "pow",   "atan2", "imin", "imax", "iabs", "fmin", "fmax", "in",    "out",
    "sets"};

/* Writes one structured register using the official assembler spelling. */
static bool emit_register(FILE *file, VirconIrRegister reg) {
  if (reg >= VIRCON_IR_REGISTER_R0 && reg <= VIRCON_IR_REGISTER_R15)
    return fprintf(file, "R%d", (int)(reg - VIRCON_IR_REGISTER_R0)) >= 0;
  if (reg == VIRCON_IR_REGISTER_SP)
    return fputs("SP", file) >= 0;
  if (reg == VIRCON_IR_REGISTER_BP)
    return fputs("BP", file) >= 0;
  return false;
}

/* Writes an immediate while retaining its chosen human-readable notation. */
static bool emit_integer(FILE *file, uint32_t value, VirconIrIntegerFormat format, unsigned hexadecimal_digits) {
  if (format == VIRCON_IR_INTEGER_SIGNED_DECIMAL)
    return fprintf(file, "%" PRId32, (int32_t)value) >= 0;
  if (format == VIRCON_IR_INTEGER_UNSIGNED_DECIMAL)
    return fprintf(file, "%" PRIu32, value) >= 0;
  if (format == VIRCON_IR_INTEGER_HEXADECIMAL)
    return fprintf(file, "0x%0*" PRIX32, (int)hexadecimal_digits, value) >= 0;
  return false;
}

/* Writes one typed instruction operand, including target memory syntax. */
static bool emit_operand(FILE *file, const VirconIrOperand *operand) {
  switch (operand->kind) {
    case VIRCON_IR_OPERAND_REGISTER:
      return emit_register(file, operand->reg);
    case VIRCON_IR_OPERAND_IMMEDIATE:
      return emit_integer(file, operand->immediate, operand->integer_format, operand->hexadecimal_digits);
    case VIRCON_IR_OPERAND_SYMBOL:
      return operand->symbol != NULL && fputs(operand->symbol, file) >= 0;
    case VIRCON_IR_OPERAND_MEMORY_REGISTER:
      if (fputc('[', file) == EOF || !emit_register(file, operand->reg))
        return false;
      if (operand->has_displacement && fprintf(file, "%+" PRId32, operand->displacement) < 0)
        return false;
      return fputc(']', file) != EOF;
    case VIRCON_IR_OPERAND_MEMORY_ABSOLUTE:
      if (fputc('[', file) == EOF ||
          !emit_integer(file, operand->immediate, operand->integer_format, operand->hexadecimal_digits))
        return false;
      return fputc(']', file) != EOF;
  }
  return false;
}

/* Serializes one structured V32 IR node without exposing formatting upstream. */
static bool emit_node(FILE *file, const VirconIrNode *node) {
  size_t index;
  const char *opcode;

  if (node->kind == VIRCON_IR_NODE_LABEL)
    return node->name != NULL && fprintf(file, "%s:\n", node->name) >= 0;
  if (node->kind == VIRCON_IR_NODE_POINTER)
    return node->name != NULL && fprintf(file, "  pointer %s\n", node->name) >= 0;
  if (node->kind != VIRCON_IR_NODE_INSTRUCTION || node->operand_count > 2)
    return false;

  opcode = node->opcode < VIRCON_IR_OPCODE_COUNT ? OPCODE_NAMES[node->opcode] : NULL;
  if (opcode == NULL || fprintf(file, "  %s", opcode) < 0)
    return false;
  for (index = 0; index < node->operand_count; ++index) {
    if (fputs(index == 0 ? " " : ", ", file) < 0 || !emit_operand(file, &node->operands[index]))
      return false;
  }
  if (node->comment != NULL && fprintf(file, "  ; %s", node->comment) < 0)
    return false;
  return fputc('\n', file) != EOF;
}

/* Serializes the structured V32 IR program to one assembler input file. */
bool emit_vircon_assembly(const VirconIrProgram *program, const char *path, Diagnostics *diagnostics) {
  FILE *file;
  size_t index;

  file = fopen(path, "w");
  if (file == NULL) {
    diagnostics_error(diagnostics, "cannot open assembly output '%s'", path);
    return false;
  }
  if (fprintf(file, "; Generated by wasm2vircon. VirconWasm v1.14.\n\n") < 0)
    goto write_failure;
  for (index = 0; index < program->count; ++index)
    if (!emit_node(file, &program->nodes[index])) {
      diagnostics_error(diagnostics, "cannot serialize invalid V32 IR node %zu", index);
      fclose(file);
      return false;
    }
  if (fclose(file) != 0) {
    diagnostics_error(diagnostics, "could not finish assembly output '%s'", path);
    return false;
  }
  return true;

write_failure:
  diagnostics_error(diagnostics, "could not write assembly output '%s'", path);
  fclose(file);
  return false;
}
