/* Assembly emitter: writes the compiler-owned V32 IR as Vircon32 source. */

#include "emitter.h"

#include <stdio.h>

/* Serializes every V32 IR line to one assembler input file. */
bool emit_vircon_assembly(const VirconIrProgram *program, const char *path,
                          Diagnostics *diagnostics) {
  FILE *file;
  size_t index;
  file = fopen(path, "w");
  if (file == NULL) {
    diagnostics_error(diagnostics, "cannot open assembly output '%s'", path);
    return false;
  }
  fprintf(file, "; Generated by wasm2vircon. VirconWasm v1.13.\n\n");
  for (index = 0; index < program->count; ++index)
    fprintf(file, "%s\n", program->instructions[index].text);
  if (fclose(file) != 0) {
    diagnostics_error(diagnostics, "could not finish assembly output '%s'",
                      path);
    return false;
  }
  return true;
}
