#include "emitter.h"

#include <inttypes.h>
#include <stdio.h>

bool emit_vircon_assembly(const VirconIrProgram *program, const char *path,
                          Diagnostics *diagnostics)
{
    FILE *file;
    size_t index;

    file = fopen(path, "w");
    if (file == NULL) {
        diagnostics_error(diagnostics, "cannot open assembly output '%s'", path);
        return false;
    }
    fprintf(file, "; Generated by wasm2vircon. VirconWasm v0.\n\n");
    for (index = 0; index < program->count; index++) {
        const VirconIrInstruction *instruction = &program->instructions[index];

        switch (instruction->op) {
        case VIRCON_IR_LABEL:
            fprintf(file, "%s:\n", instruction->label);
            break;
        case VIRCON_IR_MOV_I32:
            fprintf(file, "  mov R%d, 0x%08" PRIX32 "\n", instruction->register_number,
                    (uint32_t)instruction->i32_value);
            break;
        case VIRCON_IR_SET_BACKGROUND_COLOR:
            fprintf(file, "  out GPU_ClearColor, R%d\n", instruction->register_number);
            fprintf(file, "  out GPU_Command, GPUCommand_ClearScreen\n");
            break;
        case VIRCON_IR_END_FRAME:
            fprintf(file, "  wait\n");
            break;
        case VIRCON_IR_JUMP:
            fprintf(file, "  jmp %s\n", instruction->label);
            break;
        case VIRCON_IR_UNREACHABLE:
            fprintf(file, "  hlt  ; unreachable WebAssembly trap\n");
            break;
        case VIRCON_IR_HALT:
            fprintf(file, "  hlt\n");
            break;
        }
    }
    if (fclose(file) != 0) {
        diagnostics_error(diagnostics, "could not finish assembly output '%s'", path);
        return false;
    }
    return true;
}
